[OSPP]Support Kubernetes ConfigMap for Apollo java, golang client #79
apolloconfig/agollo pull request #318
Opened 2024-09-14 12:29 UTC by dyx1234

### What's the purpose of this PR
解决Apollo客户端在Kubernetes环境下因服务端宕机或Pod重启导致配置信息文件丢失的问题。通过使用Kubernetes ConfigMap作为新的持久化存储方案，提高配置信息的可靠性和容错性。

Solve the problem of Apollo client configuration information files being lost due to server downtime or Pod restart in the Kubernetes environment. By using Kubernetes ConfigMap as a new persistent storage solution, the reliability and fault tolerance of configuration information are improved.

discussion https://github.com/apolloconfig/apollo/discussions/5210

2024-09-27 03:00 UTC, cyruslo commented on store/configmap.go
the directory  should be named configmap instead of camelCase，camelCase is not a common mode of naming

2024-09-27 06:34 UTC, cyruslo approved these changes

2024-09-27 08:51 UTC, dyx1234 commented on store/configmap.go
> +	LoadConfigMap(configMapNamespace string) (*config.ApolloConfig, error)
Thanks a lot！ I changed it to LoadConfigMap(appConfig config.AppConfig, configMapNamespace string) (*config.ApolloConfig, error)

2024-10-19 10:35 UTC, dyx1234 commented
@zouyx PTAL

2024-10-22 08:57 UTC, cyruslo requested changes

2024-10-22 08:57 UTC, cyruslo commented on store/configmap/store.go
> +	var config = &config.ApolloConfig{}
Variable 'config' collides with imported package name

2024-10-22 08:57 UTC, cyruslo commented on store/configmap/store.go
> +	config.Configurations, _ = c.K8sManager.GetConfigMap(configMapName, configMapNamespace, key)
Suggest return the error, too

2024-10-22 12:30 UTC, dyx1234 commented on store/configmap/store.go
> +	var config = &config.ApolloConfig{}
fixed, thanks a lot

2024-10-23 08:26 UTC, cyruslo approved these changes

2024-10-24 02:13 UTC, zouyx commented on client.go
> +	if appConfig.IsBackupConfigToConfigMap {
为什么会会修改 client？我理解整体的框架应该是没有变化。
只是提供一个新的插件，通过文档告诉用户有这个插件可以选择。

我理解只需要按下方实现方式实现即可：
https://github.sheincorp.cn/zouyx/agollo_demo/tree/master/custom/file

如果是现在这种改法，可能会在用户升级的时候出现不兼容状态。
出现这种状态，可能会导致用户出现测试成本增加，或者生产故障。

2024-10-24 02:27 UTC, dyx1234 commented on client.go
> +	if appConfig.IsBackupConfigToConfigMap {
我最初是在client文件的init里，作为插件初始化的。
但是那个位置无法获取用户的配置信息（*config.AppConfig）来判断是否初始化这个插件。如果盲目初始化插件会调用GetK8sManager方法，连接不到k8s的话会直接报错。所以挪到StartWithConfig这个方法里来了。
这样会有什么问题吗，如果用户没设置IsBackupConfigToConfigMap，就不进行这个插件的初始化

2024-10-29 02:48 UTC, zouyx commented on client.go
> +	extension.AddFileHandler(&jsonFile.FileHandler{}, 2)
为什么定义优先级为 2 ？其中意义是？

2024-10-29 02:48 UTC, zouyx commented on extension/file.go
> +	sort.Slice(handlers, func(i, j int) bool {
如果优先级不能修改，为什么不是在 add 的时候排序好，而是在 get？

2024-10-29 02:48 UTC, zouyx commented on extension/file_test.go
> +	sortedHandlers := GetFileHandlers()
需要增加边界场景的排序验证，例如两个处理器为同一个优先级。
建议是使用链表的形式，如果使用数组，可能会在读取时出现排序不稳定的情况。

2024-10-29 02:48 UTC, zouyx commented on component/remote/async.go
> +		if err == nil {
如果 err 为空，但是读取的配置文件对象（c） 为空，需要继续尝试下一个 handler 吗？
按照之前同步的思想 maybe 是要的？

2024-10-29 02:48 UTC, zouyx commented on configmap/manager.go
> +			once = sync.Once{}
这个方法在使用中实际会被多次调用吗？如果不会的话，这个方式是不是不会有效果？
同时，好像没有 test case？

2024-10-29 02:48 UTC, zouyx commented on configmap/manager.go
> +	if instance == nil {
应该这个在方法最前面加个 !=nil，立刻返回这种方式才算比较高效？

2024-10-29 02:48 UTC, zouyx commented on configmap/handler.go
> +	K8sManager *K8sManager
这个不能帮用户初始化的吗？
如果不能把这个设置为私有变量，加个构造方法，不要让用户直接改这个变量。

2024-10-29 05:06 UTC, dyx1234 commented on configmap/manager.go
> +			once = sync.Once{}
正常情况是只被调用一次。但用户使用方式错误的话可能会调用多次。有必要预防吗🤔

2024-10-29 05:09 UTC, dyx1234 commented on configmap/manager.go
> +	if instance == nil {
我没注意到，这样确实会提升很多，已修改

2024-10-29 05:24 UTC, dyx1234 commented on component/remote/async.go
> +		if err == nil {
是要的，疏忽了。已优化这个循环的逻辑

2024-10-29 06:22 UTC, zouyx commented on configmap/manager.go
> +			once = sync.Once{}
我理解这个初始化 k8s 对象，只会在初始化 agollo 这个 client 的时候用到。
* 从动作层面上分析：初始化这个动作只会是一次，而不会是多次。
* 从初始化失败的处理方式上分析：要不就是重启，要不就是改代码。

所以我理解这里应该不需要预防？

2024-10-29 06:22 UTC, zouyx commented on extension/file.go
> +func AddFileHandler(handler file.FileHandler, priority ...int) {
这个 priority 为什么是个数组？

2024-10-29 06:22 UTC, zouyx commented on extension/file.go
> +func GetFileHandlers() []file.FileHandler {
这个直接返回 list 就好了吧？

2024-10-29 06:22 UTC, zouyx commented on start.go
> + * 默认的文件缓存实现的优先级为 10，具有较好的可靠性，推荐优先使用。
怎么定义这个优先级。
可能得想一下，例如已经文件缓存 Handler 默认优先级为 10。如果再设置了个 BHandler，优先级为 11 是允许的吗？

2024-10-29 06:22 UTC, zouyx commented on start.go
> -		extension.SetFileHandler(file)
这个动作不能变化，原来是 set 是替换的意思。
现在如果变成了 add 是增加的意思，只能通过增加方法的形式。

2024-10-29 06:22 UTC, zouyx commented on component/remote/async.go
> +		}
这个 log 不能直接合成一个吗？

2024-10-29 06:47 UTC, dyx1234 commented on extension/file.go
> +func AddFileHandler(handler file.FileHandler, priority ...int) {
一开始想着用户只设置一个实现的话，设为变长，用户可以不传。但不太好管理，我把它改回普通参数

2024-10-29 06:51 UTC, dyx1234 commented on start.go
> + * 默认的文件缓存实现的优先级为 10，具有较好的可靠性，推荐优先使用。
允许的吧，也可以比文件大。但是可靠性就要用户自己保证了

2024-10-29 06:59 UTC, dyx1234 commented on extension/file.go
> +func GetFileHandlers() []file.FileHandler {
直接返回handlers吗，好像破坏了封装性，不过问题不大。我改成直接返回list

2024-10-30 00:50 UTC, zouyx commented on configmap/manager.go
> +	inClusterConfig, err := rest.InClusterConfig()
这个还是得加once做单例防并发呀

2024-10-30 00:50 UTC, zouyx commented on configmap/manager.go
> +		_, err = m.clientSet.CoreV1().ConfigMaps(k8sNamespace).Update(ctx, cm, metaV1.UpdateOptions{})
这个方法是线程安全的吗？

2024-10-30 00:50 UTC, zouyx commented on configmap/manager.go
> +	configMap, err := m.clientSet.CoreV1().ConfigMaps(k8sNamespace).Get(ctx, configMapName, metaV1.GetOptions{})
这个方法是并发安全的吗？

2024-10-30 02:11 UTC, dyx1234 commented on configmap/manager.go
> +	configMap, err := m.clientSet.CoreV1().ConfigMaps(k8sNamespace).Get(ctx, configMapName, metaV1.GetOptions{})
这个是的

2024-10-30 02:12 UTC, dyx1234 commented on configmap/manager.go
> +		_, err = m.clientSet.CoreV1().ConfigMaps(k8sNamespace).Update(ctx, cm, metaV1.UpdateOptions{})
这个方法本身不是，不过SetConfigMapWithRetry对这个做了cas重试。结合kubernetes的冲突解决机制。所以综合下来是安全的

2024-10-30 10:17 UTC, zouyx commented on extension/file.go
> +		priority: 10, // 默认优先级
这个搞成常量，在设置默认值的时候，引用对应的常量

2024-10-30 10:17 UTC, zouyx commented on start.go
> +func AddConfigMapHandler(configMap file.FileHandler, priority int) {
为什么会加两个一样的方法？意义是什么？

2024-10-30 13:08 UTC, merged